meta:
    site_title: "邦强的文艺博客"
    site_subtitle: "@人生就是两盘围棋"
    site_language: "zh-cn"
    #absolute_baseurl: http://art.yanping.me
    #domain: yanping.me
    author:
        full_name:Xie Bangqiang
        short_name: bqxie
        name: bqxie
        email: bqxie@hotmail.com

#url: http://art.yanping.me

#baseurl: /base
auto: true
markdown: rdiscount

# markdown: maruku
# maruku:
#   use_divs: true
#    use_tex: true
#    png_engine : blahtex
#    png_dir    : images/latex/
#    png_url    : /images/latex/

pygments: false
permalink: /blog/:year/:month/:day/:title

disqus_short_name: haiganhongyi

      
css:
    - /css/screen.css


